<a href="https://colab.research.google.com/github/bogdanmadryga/Bogdan-Mgit/blob/main/Madryga_B_R_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Створіть одновимірний масив (вектор) з перших 10 піднесених до квадрату
# натуральних чисел та виведіть його значення.

In [5]:
import numpy as np

numbers = np.arange(1, 11)
squares = numbers ** 2

print(squares)

[  1   4   9  16  25  36  49  64  81 100]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
квадратних коренів від кожного натурального числа, починаючи з 1, та виведіть його
значення.

In [6]:
import numpy as np

matrix = np.sqrt(np.arange(1, 10)).reshape(3, 3)

print(matrix)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


3. Створіть масив розміром 3x3, заповніть його випадковими цілими числами в діапазоні
від 0 до 5 та виведіть його значення.


In [7]:
import numpy as np

matrix = np.random.randint(0, 6, size=(3, 3))

print(matrix)


[[5 2 3]
 [3 1 5]
 [3 4 4]]


4. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та обчисліть суму елементів, які менше середнього значення.


In [8]:
import numpy as np

matrix = np.random.random((5, 5))

mean_value = matrix.mean()
sum_below_mean = matrix[matrix < mean_value].sum()

print("Масив:")
print(matrix)
print("Сума елементів, які менші за середнє значення:", sum_below_mean)


Масив:
[[0.52891632 0.15324449 0.8093473  0.38903353 0.87615036]
 [0.81676606 0.09874728 0.66227826 0.57612933 0.70804153]
 [0.82091739 0.86974958 0.04693577 0.62599417 0.82553061]
 [0.30499875 0.03429776 0.87383731 0.15133091 0.56638114]
 [0.8426873  0.68302692 0.44753669 0.33616752 0.84961226]]
Сума елементів, які менші за середнє значення: 2.491209007129262


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими
числами від 1 до 30 та виконайте на них поелементні операції додавання, віднімання
та множення.


In [9]:
import numpy as np

array1 = np.random.randint(1, 31, size=5)
array2 = np.random.randint(1, 31, size=5)

sum_result = array1 + array2
difference_result = array1 - array2
multiplication_result = array1 * array2

print("Масив 1:", array1)
print("Масив 2:", array2)
print("Сума масивів:", sum_result)
print("Різниця масивів:", difference_result)
print("Множення масивів:", multiplication_result)


Масив 1: [26 12 11 22 29]
Масив 2: [ 4 10 26 17  5]
Сума масивів: [30 22 37 39 34]
Різниця масивів: [ 22   2 -15   5  24]
Множення масивів: [104 120 286 374 145]


6. Створіть дві матриці 3x3, заповніть їх довільними дійсними числами від 0 до 1 та
знайдіть їх добуток.


In [10]:
import numpy as np

matrix1 = np.random.random((3, 3))
matrix2 = np.random.random((3, 3))

product = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(product)


Матриця 1:
[[0.86468639 0.56164696 0.47304304]
 [0.21983309 0.36665841 0.22508365]
 [0.54060024 0.06780147 0.26459319]]
Матриця 2:
[[0.76666205 0.7082875  0.25146064]
 [0.90724259 0.45599892 0.18432283]
 [0.77200963 0.05114234 0.61642288]]
Добуток матриць:
[[1.53766606 0.8927495  0.6125535 ]
 [0.67495256 0.33441217 0.2616096 ]
 [0.68023856 0.42734971 0.31153834]]


7. Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [11]:
import numpy as np

matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 2))

product = np.dot(matrix1, matrix2)

print("Матриця 1 (2x3):")
print(matrix1)
print("Матриця 2 (3x2):")
print(matrix2)
print("Добуток матриць:")
print(product)


Матриця 1 (2x3):
[[5 2 1]
 [3 5 4]]
Матриця 2 (3x2):
[[1 3]
 [2 3]
 [4 3]]
Добуток матриць:
[[13 24]
 [29 36]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть її обернену матрицю.


In [12]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))

# Перевірка на те, чи матриця невироджена (має обернену матрицю)
if np.linalg.det(matrix) != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("Матриця:")
    print(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
else:
    print("Матриця невироджена, обернену матрицю не знайдено.")


Матриця:
[[1 6 8]
 [7 6 7]
 [5 6 5]]
Обернена матриця:
[[-1.42857143e-01  2.14285714e-01 -7.14285714e-02]
 [-4.31753398e-17 -4.16666667e-01  5.83333333e-01]
 [ 1.42857143e-01  2.85714286e-01 -4.28571429e-01]]


9. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та транспонуйте її.


In [13]:
import numpy as np

matrix = np.random.random((5, 5))

transposed_matrix = matrix.T

print("Матриця:")
print(matrix)
print("Транспонована матриця:")
print(transposed_matrix)


Матриця:
[[0.89764335 0.21267689 0.92506305 0.91793652 0.07633334]
 [0.54659327 0.30457726 0.70572    0.2564768  0.51169726]
 [0.81684472 0.70955744 0.55564187 0.50783334 0.60620203]
 [0.58915978 0.77450929 0.82706739 0.93299156 0.6046135 ]
 [0.39708703 0.18555253 0.83664627 0.80164828 0.46870409]]
Транспонована матриця:
[[0.89764335 0.54659327 0.81684472 0.58915978 0.39708703]
 [0.21267689 0.30457726 0.70955744 0.77450929 0.18555253]
 [0.92506305 0.70572    0.55564187 0.82706739 0.83664627]
 [0.91793652 0.2564768  0.50783334 0.93299156 0.80164828]
 [0.07633334 0.51169726 0.60620203 0.6046135  0.46870409]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими цілими числами в діапазоні від -5 до 5, а вектор - випадковими дійсними
числами від 0 до 1 і знайдіть добуток матриці на вектор.


In [14]:
import numpy as np

matrix = np.random.randint(-5, 6, size=(3, 4))  # Матриця 3x4 з цілими числами в діапазоні від -5 до 5
vector = np.random.random((4, 1))  # Вектор 4x1 з дійсними числами в діапазоні від 0 до 1

product = np.dot(matrix, vector)  # Добуток матриці та вектора

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Добуток матриці та вектора:")
print(product)


Матриця:
[[-1  0  4  3]
 [-1  1 -1  3]
 [ 3 -2  1  1]]
Вектор:
[[0.92156467]
 [0.62925149]
 [0.17667933]
 [0.61775765]]
Добуток матриці та вектора:
[[1.63842562]
 [1.38428044]
 [2.30062802]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор.

In [15]:
import numpy as np

matrix = np.random.random((2, 3))  # Матриця 2x3 з дійсними числами від 0 до 1
vector = np.random.random((3, 1))  # Вектор 3x1 з дійсними числами від 0 до 1

product = np.dot(matrix, vector)  # Добуток матриці та вектора

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Добуток матриці та вектора:")
print(product)


Матриця:
[[0.23441627 0.09283332 0.50486841]
 [0.72049456 0.99619988 0.46140354]]
Вектор:
[[0.36603635]
 [0.20479061]
 [0.34534956]]
Добуток матриці та вектора:
[[0.27917235]
 [0.62708509]]


12.Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць.

In [16]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(3, 3))  # Перша матриця 3x3 з цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(3, 3))  # Друга матриця 3x3 з цілими числами від 1 до 10

sum_matrix1 = matrix1.sum()  # Сума елементів першої матриці
sum_matrix2 = matrix2.sum()  # Сума елементів другої матриці

total_sum = sum_matrix1 + sum_matrix2  # Сума всіх елементів обох матриць

print("Матриця 1:")
print(matrix1)
print("Сума елементів першої матриці:", sum_matrix1)
print("Матриця 2:")
print(matrix2)
print("Сума елементів другої матриці:", sum_matrix2)
print("Сума всіх елементів обох матриць:", total_sum)


Матриця 1:
[[10  5  1]
 [ 8  2  7]
 [ 9  4  1]]
Сума елементів першої матриці: 47
Матриця 2:
[[1 3 1]
 [3 5 8]
 [4 1 3]]
Сума елементів другої матриці: 29
Сума всіх елементів обох матриць: 76


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть різницю їх елементів.


In [17]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 2))  # Перша матриця 2x2 з цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(2, 2))  # Друга матриця 2x2 з цілими числами від 1 до 10

difference = matrix1 - matrix2  # Різниця між елементами двох матриць

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Різниця матриць:")
print(difference)


Матриця 1:
[[4 2]
 [5 2]]
Матриця 2:
[[5 5]
 [7 7]]
Різниця матриць:
[[-1 -3]
 [-2 -5]]


14. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 5 та знайдіть кількість парних елементів матриці.

In [18]:
import numpy as np

matrix = np.random.randint(1, 6, size=(3, 3))  # Матриця 3x3 з цілими числами від 1 до 5

# Підрахунок парних елементів
even_count = np.count_nonzero(matrix % 2 == 0)

print("Матриця:")
print(matrix)
print("Кількість парних елементів:", even_count)


Матриця:
[[1 2 4]
 [1 5 4]
 [2 1 3]]
Кількість парних елементів: 4


15. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму кубів елементів
кожного рядка матриці.

In [19]:
import numpy as np

matrix = np.random.uniform(-1, 1, size=(4, 4))  # Матриця 4x4 з дійсними числами від -1 до 1

# Обчислення суми кубів елементів кожного рядка
sum_of_cubes = np.sum(matrix**3, axis=1)

print("Матриця:")
print(matrix)
print("Вектор-стовпчик з сумою кубів елементів кожного рядка:")
print(sum_of_cubes)


Матриця:
[[ 0.67979088 -0.09862688  0.38316796  0.2238155 ]
 [ 0.82754019 -0.69005798 -0.24292086 -0.7256458 ]
 [ 0.58761773  0.5159829  -0.7103416  -0.14338183]
 [-0.61280336  0.79872557 -0.07933256  0.32835743]]
Вектор-стовпчик з сумою кубів елементів кожного рядка:
[ 0.38065014 -0.15830573 -0.02109987  0.31433595]
